# Generated by Django 3.0.6 on 2020-05-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=255)),
                ('IIN', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=255)),
                ('Latin_First_Name', models.CharField(max_length=255)),
                ('Latin_Last_Name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
            ],
        ),
    ]
