# Generated by Django 3.0.6 on 2020-05-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('credit_amount', models.CharField(max_length=255)),
                ('internal_code', models.CharField(max_length=255)),
                ('monthly_payment', models.CharField(max_length=255)),
                ('signed_by', models.CharField(max_length=255)),
                ('signed_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.CharField(max_length=255)),
                ('request_date', models.DateField()),
                ('request_status', models.CharField(max_length=255)),
                ('request_type', models.CharField(max_length=255)),
                ('response_body', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen', models.CharField(max_length=255)),
                ('created_date', models.DateField(max_length=255)),
                ('offer_amount', models.CharField(max_length=255)),
                ('offered_monthly_payment', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.CharField(max_length=255)),
                ('income_type', models.CharField(max_length=255)),
                ('request_id', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('BIC', models.CharField(max_length=255)),
                ('BIN', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('request_id', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
    ]
