# Generated by Django 3.0.6 on 2020-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cb_data_table_external_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cb_data_table',
            name='external_contract_number',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
