# Generated by Django 3.0.6 on 2020-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200517_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regional_Gcvp_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
                ('avg_income', models.IntegerField()),
            ],
        ),
    ]
