# Generated by Django 3.0.6 on 2020-05-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sms_code',
            field=models.CharField(default=1111, max_length=4),
        ),
    ]
