# Generated by Django 3.0.6 on 2020-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_application_sms_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cb_Data_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.CharField(max_length=12)),
                ('monthly_payment', models.IntegerField()),
                ('actual_dpd', models.IntegerField()),
                ('historical_dpd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gbdfl_Data_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.CharField(max_length=12)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gcvp_Data_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.CharField(max_length=12)),
                ('monthly_income', models.IntegerField()),
            ],
        ),
    ]
