# Generated by Django 3.0.6 on 2020-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cb_data_table_gbdfl_data_table_gcvp_data_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cb_data_table',
            name='external_contract_number',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
