# Generated by Django 3.0.6 on 2020-05-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_application_internal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
